language: objective-c
osx_image: xcode8
rvm:
  - 2.3.1

install:
  - bundle install
  - bundle exec pod repo update --silent
  - bundle exec pod install

script:
  - xcodebuild -workspace 'RxTodo.xcworkspace' -scheme 'RxTodo' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
